apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8.4
          imagePullPolicy: Never
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: zookeeper-env
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-pvc