keycloak:
  auth-server-url: http://localhost:8888
  realm: tournaments
  client-id: admin-cli
  client-secret: nUrAUYb1Q09zF1HmFgYk7FlnVdlMl0LR

  user-client-id: user
  user-client-secret: L5XUWUCutsXlXT0x0qcULSDQuznYqqvW
  grant-type: password


server:
  port: 8020

spring:
  application:
    name: user

  config:
    import: optional:configserver:http://localhost:8000

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: nikita
    password: 1234

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        default_schema: users

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8888/realms/tournaments
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9090/realms/OauthTests
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: myclient
#            client-secret: SECRET
#            scope: openid

  liquibase:
    enabled: true
    change-log: liquibase/changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}

logging:
#  config: classpath:/logging/logback-spring.xml
  level:
    org:
      hibernate.orm.jdbc.bind: TRACE
#      elasticsearch.client: TRACE
      springframework:
    #        security: TRACE
        jdbc.core: TRACE
        cloud:
          openfeign: TRACE
#        cache: TRACE
#        data:
#          redis:
#            core: TRACE

