POST http://localhost:8888/realms/tournaments/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

#client_id=user&
#client_secret=L5XUWUCutsXlXT0x0qcULSDQuznYqqvW&
#username=string2&
#password=string&
#grant_type=password
client_id=team&
client_secret=Kbv9nt2poEYXtJxu9AftT6ef6a1wmV4Q&
grant_type=client_credentials



#
# curl -X POST "http://localhost:8888/realms/tournaments/protocol/openid-connect/token"
#     -H "Content-Type: application/x-www-form-urlencoded"
#     -d "client_id=user"
#     -d "client_secret=QI7KkiBpFF5EAAkR3Z3MNCl6wtMmsdl1"
#     -d "username=nikita"
#     -d "password=1234"
#     -d "grant_type=password"



