apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: bitnami/zipkin:3.4.2
          ports:
            - containerPort: 9411
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"