apiVersion: v1
kind: Service
metadata:
  name: postgres-for-notification-service
spec:
  selector:
    app: postgres-for-notification-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432