apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification

  template:
    metadata:
      labels:
        app: notification

    spec:
      containers:
        - name: notification-service
          image: mindless35/tournaments:notification-service-1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8060
          envFrom:
            - configMapRef:
                name: common-config-env
            - configMapRef:
                name: notification-config-env
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: common-db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-db-credentials
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"