apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-postgres-init
data:
  init-postgres.sql: |
    CREATE SCHEMA IF NOT EXISTS notifications;
    DROP SCHEMA IF EXISTS public CASCADE;
    DROP DATABASE IF EXISTS postgres;