apiVersion: v1
kind: ConfigMap
metadata:
  name: team-postgres-init
data:
  init-postgres.sql: |
    CREATE SCHEMA IF NOT EXISTS teams;
    DROP SCHEMA IF EXISTS public CASCADE;
    DROP DATABASE IF EXISTS postgres;