apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team
  template:
    metadata:
      labels:
        app: team
    spec:
      containers:
        - name: team-service
          image: mindless35/tournaments:team-service-1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8030
          envFrom:
            - configMapRef:
                name: common-config-env
            - configMapRef:
                name: team-config-env
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: common-db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-db-credentials
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"