server:
  port: 8060

spring:
  application:
    name: notification

  config:
    import: optional:configserver:http://localhost:8000

  datasource:
    url: jdbc:postgresql://localhost:5436/notification
    username: nikita
    password: 1234

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        default_schema: notifications

  kafka:
    template:
      default-topic: notifications
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifications-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: "*"
          type.mapping: notificationMessage:com.microservices.notification.dto.kafka.NotificationMessage


  mail:
    host: smtp.gmail.com
    port: 587
    username: readingbooksjms@gmail.com
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    enabled: true
    change-log: liquibase/changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: TRACE
      springframework:
        jdbc.core: TRACE
        kafka: INFO
    org.apache:
      http: TRACE
      kafka: INFO
