package com.microservices.notification.enums;

public enum NotificationType {
    TOURNAMENT_APPROVED,
    TOURNAMENT_REGISTRATION,
    TOURNAMENT_STARTED,
    TOURNAMENT_ENDED,

    MATCH_SCHEDULED,
    MATCH_REMINDER,
    MATCH_RESULT,

    USER_REGISTRATION,
    PASSWORD_RESET,
    ACCOUNT_ACTIVATION,
    EMAIL_CHANGED

}
