spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8000

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: