apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:26.0.5-debian-12-r1
          envFrom:
            - configMapRef:
                name: keycloak-env
            - secretRef:
                name: keycloak-secret
            - secretRef:
                name: keycloak-postgres-secret
          env:
            - name: KEYCLOAK_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: keycloak-postgres-env
                  key: POSTGRES_DB
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"