apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.9.0
          envFrom:
            - configMapRef:
                name: kafka-env
          ports:
            - containerPort: 9092
            - containerPort: 9093
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc