apiVersion: v1
kind: ConfigMap
metadata:
  name: match-postgres-init
data:
  init-postgres.sql: |
    CREATE SCHEMA IF NOT EXISTS matches;
    DROP SCHEMA IF EXISTS public CASCADE;
    DROP DATABASE IF EXISTS postgres;