apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: config-server

  template:
    metadata:
      labels:
        components: config-server

    spec:
      containers:
        - name: config-server
          image: config-server:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"