apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: notification

  template:
    metadata:
      labels:
        components: notification

    spec:
      containers:
        - name: notification-service
          image: notification-service:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"