apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: team

  template:
    metadata:
      labels:
        components: team

    spec:
      containers:
        - name: team-service
          image: team-service:1.0
          ports:
            - containerPort: 8030
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"