apiVersion: apps/v1
kind: Deployment
metadata:
  name: tournament-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: tournament

  template:
    metadata:
      labels:
        components: tournament

    spec:
      containers:
        -
        - name: tournament-service
          image: tournament-service:1.0
          ports:
            - containerPort: 8040
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"



