apiVersion: v1
kind: Service
metadata:
  name: postgres-for-tournament-service
spec:
  selector:
    app: postgres-for-tournament-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432