apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-tournament-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard