apiVersion: v1
kind: ConfigMap
metadata:
  name: tournament-postgres-init
data:
  init-postgres.sql: |
    CREATE SCHEMA IF NOT EXISTS tournaments;
    DROP SCHEMA IF EXISTS public CASCADE;
    DROP DATABASE IF EXISTS postgres;