spring:
  application:
    name: config-server

  config:
    import: classpath:/config/application.yml

  profiles:
    active:
      - native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          #git:
          #   uri: https://github.com/ihuaylupo/config.git
          #   searchPaths: licensingservice

server:
  port: 8000

#encrypt: todo add encrypt key and git repo config
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo