server:
  port: 8000

spring:
  application:
    name: config-server

  config:
    import: classpath:/config/application.yml

  profiles:
    active:
      - native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          #git:
          #   uri: https://github.com/ihuaylupo/config.git
          #   searchPaths: licensingservice

#encrypt: todo add encrypt key and git repo config
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
        "[method.timed.metric]": true
        percentiles:
          "[http.server.requests]": true
        sla:
          "[http.server.requests]": true
        minimum-expected-value:
          "[http.server.requests]": true
        maximum-expected-value:
          "[http.server.requests]": true