eureka:
  instance:
    prefer-ip-address: true
#    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0