eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka
      
management:
  tracing:
    sampling:
      probability: 1.0