eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
        "[method.timed.metric]": true
        percentiles:
          "[http.server.requests]": true
        sla:
          "[http.server.requests]": true
        minimum-expected-value:
          "[http.server.requests]": true
        maximum-expected-value:
          "[http.server.requests]": true
