server:
  port: 8010

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: match
          uri: lb:http://match
          predicates:
            - Path=/api/v1/matches/**

        - id: team
          uri: lb:http://team
          predicates:
            - Path=/api/v1/teams/**

        - id: tournament
          uri: lb:http://tournament
          predicates:
            - Path=/api/v1/tournaments/**

        - id: user
          uri: lb:http://user
          predicates:
            - Path=/api/v1/users/**