apiVersion: v1
kind: ConfigMap
metadata:
  name: user-postgres-init
data:
  init-postgres.sql: |
    CREATE SCHEMA IF NOT EXISTS users;
    DROP SCHEMA IF EXISTS public CASCADE;
    DROP DATABASE IF EXISTS postgres;